# Example
# https://gitpod.io/#https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TSconfig/tree/main

image: gitpod/workspace-full

tasks:
  - name: RenderT3Docs
    init: |
      docker pull ghcr.io/t3docs/render-documentation:v3.0.dev28 
      docker tag ghcr.io/t3docs/render-documentation:v3.0.dev28 t3docs/render-documentation:develop

    command: |
      eval "$(docker run --rm t3docs/render-documentation:develop show-shell-commands)"
      dockrun_t3rd makehtml-no-cache
      gp open ./Documentation-GENERATED-temp/Result/project/0.0.0/_buildinfo/warnings.txt
      cd ./Documentation-GENERATED-temp/Result/project/0.0.0/ 
      nohup php -S localhost:8001 &
      gp preview "$(gp url 8001)/Index.html" --external

ports:
  - port: 8001
    name: t3docspreview
    onOpen: ignore
