@startuml

skinparam dpi 150
hide empty members

skinparam sequence {
    ArrowColor  #e18d00
    DividerBackgroundColor  #f7a831
    GroupBackgroundColor    #f7a831
    LifeLineBackgroundColor white
    LifeLineBorderColor #e18d00
    ParticipantBackgroundColor  #f7a831
    ParticipantBorderColor  #e18d00
    BoxLineColor    #e18d00
    BoxBackgroundColor  #DDDDDD
}

participant Application
participant ServerRequestFactory
participant MiddlewareStackResolver

participant "MiddlewareDispatcher \n(RequestHandlerInterface)" as MiddlewareDispatcher

box "Middleware A"
participant "Anonymous\nRequestHandler" as RequestHandlerA << Generated >>
participant "MiddlewareA" as Middleware
end box

box "Middleware B"
participant "Anonymous\nRequestHandler" as RequestHandlerB << Generated >>
participant "MiddlewareB" as MiddlewareB
end box

participant "(Frontend|Backend)\nRequestHandler" as RequestHandler

note over Middleware
Every Middleware
 is wrapped in
  an anonymous
 RequestHandler
end note

note over RequestHandler
Always the last
RequestHandler
in the stack
end note



autonumber 1
Application -> ServerRequestFactory: fromGlobals()
autonumber 1
Application <-- ServerRequestFactory: Request

autonumber 2
Application -> MiddlewareStackResolver: resolve()
autonumber 3
Application <-- MiddlewareStackResolver: Stack

autonumber 4
Application -> MiddlewareDispatcher: handle(Request)
autonumber 4
MiddlewareDispatcher -> RequestHandlerA: handle(Request)

autonumber 5
RequestHandlerA -> Middleware: process(Request, \nnext RequestHandler)
autonumber 5
Middleware -> RequestHandlerB : handle(Request)
autonumber 5
RequestHandlerB -> MiddlewareB: process(Request, \nnext RequestHandler)

autonumber 6
MiddlewareB -> RequestHandler : handle(Request)
autonumber 6
RequestHandler --> MiddlewareB: Response


autonumber 7
MiddlewareB --> RequestHandlerB: Response

autonumber 7
RequestHandlerB --> Middleware: Response


autonumber 7
Middleware --> RequestHandlerA: Response

autonumber 8
RequestHandlerA --> MiddlewareDispatcher: Response
autonumber 8
MiddlewareDispatcher --> Application: Response

@enduml