<?php

return [
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Database\Middleware\UsableForConnectionInterface::class,
        'members' => [
            'canBeUsedForConnection',
        ],
        'targetFileName' => 'CodeSnippets/Manual/Database/UsableForConnectionInterface.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Database\Query\Expression\ExpressionBuilder::class,
        'targetFileName' => 'ApiOverview/Database/DoctrineDbal/ExpressionBuilder/_ExpressionBuilderLength.rst.txt',
        'includeClassComment' => false,
        'members' => [
            'length',
        ],
        'withCode' => false,
        'noindexInClass' => true,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Database\Query\Expression\ExpressionBuilder::class,
        'targetFileName' => 'ApiOverview/Database/DoctrineDbal/ExpressionBuilder/_ExpressionBuilderTrim.rst.txt',
        'includeClassComment' => false,
        'members' => [
            'trim',
        ],
        'withCode' => false,
        'noindexInClass' => true,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Database\Query\Expression\ExpressionBuilder::class,
        'targetFileName' => 'ApiOverview/Database/DoctrineDbal/ExpressionBuilder/_ExpressionBuilderAggregate.rst.txt',
        'includeClassComment' => false,
        'members' => [
            'min', 'max', 'avg', 'sum', 'count',
        ],
        'withCode' => false,
        'noindexInClass' => true,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Database\Query\Expression\ExpressionBuilder::class,
        'targetFileName' => 'ApiOverview/Database/DoctrineDbal/ExpressionBuilder/_ExpressionBuilderComparisons.rst.txt',
        'includeClassComment' => false,
        'members' => [
            'eq', 'neq', 'lt', 'lte', 'gt', 'gte', 'isNull', 'isNotNull', 'like', 'notLike', 'in', 'notIn', 'inSet', 'notInSet', 'bitAnd',
        ],
        'withCode' => false,
        'noindexInClass' => true,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Database\Query\Expression\ExpressionBuilder::class,
        'targetFileName' => 'ApiOverview/Database/DoctrineDbal/ExpressionBuilder/_ExpressionBuilderAs.rst.txt',
        'includeClassComment' => false,
        'includeMemberComment' => false,
        'members' => [
            'as',
        ],
        'withCode' => false,
        'noindexInClass' => true,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Database\Query\Expression\ExpressionBuilder::class,
        'targetFileName' => 'ApiOverview/Database/DoctrineDbal/ExpressionBuilder/_ExpressionBuilderConcat.rst.txt',
        'includeClassComment' => false,
        'includeMemberComment' => false,
        'members' => [
            'concat',
        ],
        'withCode' => false,
        'noindexInClass' => true,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Database\Query\Expression\ExpressionBuilder::class,
        'targetFileName' => 'ApiOverview/Database/DoctrineDbal/ExpressionBuilder/_ExpressionBuilderCastVarchar.rst.txt',
        'includeClassComment' => false,
        'includeMemberComment' => false,
        'members' => [
            'castVarchar',
        ],
        'withCode' => false,
        'noindexInClass' => true,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Database\Query\Expression\ExpressionBuilder::class,
        'targetFileName' => 'ApiOverview/Database/DoctrineDbal/ExpressionBuilder/_ExpressionBuilderCastInt.rst.txt',
        'includeClassComment' => false,
        'includeMemberComment' => false,
        'members' => [
            'castInt',
        ],
        'withCode' => false,
        'noindexInClass' => true,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Database\Query\Expression\ExpressionBuilder::class,
        'targetFileName' => 'ApiOverview/Database/DoctrineDbal/ExpressionBuilder/_ExpressionBuilderRepeat.rst.txt',
        'includeClassComment' => false,
        'includeMemberComment' => false,
        'members' => [
            'repeat',
        ],
        'withCode' => false,
        'noindexInClass' => true,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Database\Query\Expression\ExpressionBuilder::class,
        'targetFileName' => 'ApiOverview/Database/DoctrineDbal/ExpressionBuilder/_ExpressionBuilderSpace.rst.txt',
        'includeClassComment' => false,
        'includeMemberComment' => false,
        'members' => [
            'space',
        ],
        'withCode' => false,
        'noindexInClass' => true,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Database\Query\Expression\ExpressionBuilder::class,
        'targetFileName' => 'ApiOverview/Database/DoctrineDbal/ExpressionBuilder/_ExpressionBuilderLeft.rst.txt',
        'includeClassComment' => false,
        'includeMemberComment' => false,
        'members' => [
            'left',
        ],
        'withCode' => false,
        'noindexInClass' => true,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Database\Query\Expression\ExpressionBuilder::class,
        'targetFileName' => 'ApiOverview/Database/DoctrineDbal/ExpressionBuilder/_ExpressionBuilderRight.rst.txt',
        'includeClassComment' => false,
        'includeMemberComment' => false,
        'members' => [
            'right',
        ],
        'withCode' => false,
        'noindexInClass' => true,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Database\Query\Expression\ExpressionBuilder::class,
        'targetFileName' => 'ApiOverview/Database/DoctrineDbal/ExpressionBuilder/_ExpressionBuilderLeftPad.rst.txt',
        'includeClassComment' => false,
        'includeMemberComment' => false,
        'members' => [
            'leftPad',
        ],
        'withCode' => false,
        'noindexInClass' => true,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Database\Query\Expression\ExpressionBuilder::class,
        'targetFileName' => 'ApiOverview/Database/DoctrineDbal/ExpressionBuilder/_ExpressionBuilderRightPad.rst.txt',
        'includeClassComment' => false,
        'includeMemberComment' => false,
        'members' => [
            'RightPad',
        ],
        'withCode' => false,
        'noindexInClass' => true,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Database\Query\Expression\ExpressionBuilder::class,
        'targetFileName' => 'ApiOverview/Database/DoctrineDbal/ExpressionBuilder/_ExpressionBuilderIf.rst.txt',
        'includeClassComment' => false,
        'includeMemberComment' => false,
        'members' => [
            'If',
        ],
        'withCode' => false,
        'noindexInClass' => true,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Database\Query\Expression\ExpressionBuilder::class,
        'targetFileName' => 'ApiOverview/Database/DoctrineDbal/ExpressionBuilder/_ExpressionBuilder.rst.txt',
        'includeMemberComment' => false,
        'members' => [
            '__construct',
        ],
        'withCode' => false,
    ],
];
