@startuml
skinparam nodesep 10
skinparam ranksep 20

rectangle "System Groups" #line.dotted {
  rectangle "PG_website_a" as PG_website_a #Application
  rectangle "DBM_website_a" as DBM_website_a #Application
  rectangle "DBM_website_a_survey" as DBM_website_a_survey #Application
  rectangle "FM_website_a" as FM_website_a #Application
  rectangle "FM_website_a_survey" as FM_website_a_survey #Application
  rectangle "CM_website_a" as CM_website_a #Application
  rectangle "FO_all" as FO_all #Application
  rectangle "L_all" as L_all #Application
  PG_website_a -[hidden]-> DBM_website_a
  DBM_website_a -[hidden]-> DBM_website_a_survey
  DBM_website_a_survey -[hidden]-> FM_website_a
  FM_website_a -[hidden]-> FM_website_a_survey
  FM_website_a_survey -[hidden]-> CM_website_a
  CM_website_a -[hidden]-> FO_all
  FO_all -[hidden]-> L_all
}

rectangle "Access Control List Groups" #line.dotted {
  rectangle "ACL_content_elements" as ACL_content_elements #Technology
  rectangle "ACL_news" as ACL_news #Technology
  rectangle "ACL_gallery" as ACL_gallery #Technology
  rectangle "ACL_survey" as ACL_survey #Technology
  ACL_content_elements -[hidden]-> ACL_news
  ACL_news -[hidden]-> ACL_gallery
  ACL_gallery -[hidden]-> ACL_survey
}
@enduml
