<?php

return [
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\AfterFileAddedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/AfterFileAddedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\AfterFileAddedToIndexEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/AfterFileAddedToIndexEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\AfterFileCommandProcessedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/AfterFileCommandProcessedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\AfterFileContentsSetEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/AfterFileContentsSetEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\AfterFileCopiedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/AfterFileCopiedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\AfterFileCreatedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/AfterFileCreatedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\AfterFileDeletedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/AfterFileDeletedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\AfterFileMarkedAsMissingEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/AfterFileMarkedAsMissingEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\AfterFileMetaDataCreatedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/AfterFileMetaDataCreatedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\AfterFileMetaDataDeletedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/AfterFileMetaDataDeletedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\AfterFileMovedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/AfterFileMovedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\AfterFileProcessingEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/AfterFileProcessingEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\AfterFileRemovedFromIndexEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/AfterFileRemovedFromIndexEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\AfterFileRenamedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/AfterFileRenamedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\AfterFileReplacedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/AfterFileReplacedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\AfterFileUpdatedInIndexEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/AfterFileUpdatedInIndexEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\AfterFolderAddedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/AfterFolderAddedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\AfterFolderCopiedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/AfterFolderCopiedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\AfterFolderDeletedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/AfterFolderDeletedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\AfterFolderMovedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/AfterFolderMovedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\AfterFolderRenamedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/AfterFolderRenamedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\AfterResourceStorageInitializationEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/AfterResourceStorageInitializationEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\BeforeFileAddedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/BeforeFileAddedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\BeforeFileContentsSetEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/BeforeFileContentsSetEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\BeforeFileCopiedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/BeforeFileCopiedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\BeforeFileCreatedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/BeforeFileCreatedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\BeforeFileDeletedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/BeforeFileDeletedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\BeforeFileMovedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/BeforeFileMovedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\BeforeFileProcessingEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/BeforeFileProcessingEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\BeforeFileRenamedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/BeforeFileRenamedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\BeforeFileReplacedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/BeforeFileReplacedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\BeforeFolderAddedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/BeforeFolderAddedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\BeforeFolderCopiedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/BeforeFolderCopiedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\BeforeFolderDeletedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/BeforeFolderDeletedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\BeforeFolderMovedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/BeforeFolderMovedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\BeforeFolderRenamedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/BeforeFolderRenamedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\BeforeResourceStorageInitializationEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/BeforeResourceStorageInitializationEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\EnrichFileMetaDataEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/EnrichFileMetaDataEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\GeneratePublicUrlForResourceEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/GeneratePublicUrlForResourceEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\ModifyFileDumpEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/ModifyFileDumpEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Imaging\Event\ModifyIconForResourcePropertiesEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/ModifyIconForResourcePropertiesEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\SanitizeFileNameEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/SanitizeFileNameEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Core\Resource\Event\AfterFileMetaDataUpdatedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Core/Resource/AfterFileMetaDataUpdatedEvent.rst.txt',
        'withCode' => false,
    ],
];
