<?php

return [
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\View\Event\IsContentUsedOnPageLayoutEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/IsContentUsedOnPageLayoutEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\View\Event\ModifyDatabaseQueryForContentEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/ModifyDatabaseQueryForContentEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\View\Event\PageContentPreviewRenderingEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/PageContentPreviewRenderingEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\Controller\Event\AfterFormEnginePageInitializedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/AfterFormEnginePageInitializedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\History\Event\AfterHistoryRollbackFinishedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/AfterHistoryRollbackFinishedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\Controller\Event\AfterPageColumnsSelectedForLocalizationEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/AfterPageColumnsSelectedForLocalizationEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\Routing\Event\AfterPagePreviewUriGeneratedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/AfterPagePreviewUriGeneratedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\Controller\Event\BeforeFormEnginePageInitializedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/BeforeFormEnginePageInitializedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\History\Event\BeforeHistoryRollbackStartEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/BeforeHistoryRollbackStartEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\Routing\Event\BeforePagePreviewUriGeneratedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/BeforePagePreviewUriGeneratedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\Backend\Event\ModifyClearCacheActionsEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/ModifyClearCacheActionsEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\LoginProvider\Event\ModifyPageLayoutOnLoginProviderSelectionEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/ModifyPageLayoutOnLoginProviderSelectionEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\Authentication\Event\SwitchUserEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/SwitchUserEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\Backend\Event\SystemInformationToolbarCollectorEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/SystemInformationToolbarCollectorEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\Search\Event\ModifyQueryForLiveSearchEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/ModifyQueryForLiveSearchEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\Controller\Event\ModifyPageLayoutContentEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/ModifyPageLayoutContentEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\Controller\Event\ModifyNewContentElementWizardItemsEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/ModifyNewContentElementWizardItemsEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\Form\Event\ModifyLinkExplanationEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/ModifyLinkExplanationEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\Form\Event\ModifyInlineElementEnabledControlsEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/ModifyInlineElementEnabledControlsEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\Form\Event\ModifyInlineElementControlsEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/ModifyInlineElementControlsEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\Form\Event\ModifyImageManipulationPreviewUrlEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/ModifyImageManipulationPreviewUrlEvent.rst.txt',
        'withCode' => false,
    ],
    // TYPO3 v12.0
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\Controller\Event\ModifyGenericBackendMessagesEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/ModifyGenericBackendMessagesEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => TYPO3\CMS\Backend\Module\BeforeModuleCreationEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/BeforeModuleCreationEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => TYPO3\CMS\Backend\Controller\Event\AfterBackendPageRenderEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/AfterBackendPageRenderEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\Controller\Event\AfterPageTreeItemsPreparedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/AfterPageTreeItemsPreparedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\Form\Event\ModifyEditFormUserAccessEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/ModifyEditFormUserAccessEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\Controller\Event\RenderAdditionalContentToRecordListEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/RenderAdditionalContentToRecordListEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\RecordList\Event\ModifyRecordListHeaderColumnsEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/ModifyRecordListHeaderColumnsEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\RecordList\Event\ModifyRecordListRecordActionsEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/ModifyRecordListRecordActionsEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\RecordList\Event\ModifyRecordListTableActionsEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/ModifyRecordListTableActionsEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => TYPO3\CMS\Backend\Controller\Event\ModifyLinkHandlersEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/ModifyLinkHandlersEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => TYPO3\CMS\Backend\Controller\Event\ModifyAllowedItemsEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/ModifyAllowedItemsEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => TYPO3\CMS\Backend\View\Event\ModifyDatabaseQueryForRecordListingEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/ModifyDatabaseQueryForRecordListingEvent.rst.txt',
        'withCode' => false,

    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => TYPO3\CMS\Backend\Form\Event\CustomFileControlsEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/CustomFileControlsEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => TYPO3\CMS\Backend\Form\Event\ModifyFileReferenceControlsEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/ModifyFileReferenceControlsEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => TYPO3\CMS\Backend\Form\Event\ModifyFileReferenceEnabledControlsEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/ModifyFileReferenceEnabledControlsEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\Controller\Event\AfterRecordSummaryForLocalizationEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/AfterRecordSummaryForLocalizationEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\Search\Event\BeforeSearchInDatabaseRecordProviderEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/BeforeSearchInDatabaseRecordProviderEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\ElementBrowser\Event\IsFileSelectableEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/IsFileSelectableEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\Search\Event\ModifyResultItemInLiveSearchEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/ModifyResultItemInLiveSearchEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\Template\Components\ModifyButtonBarEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/ModifyButtonBarEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\RecordList\Event\BeforeRecordDownloadIsExecutedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/BeforeRecordDownloadIsExecutedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\RecordList\Event\BeforeRecordDownloadPresetsAreDisplayedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/BeforeRecordDownloadPresetsAreDisplayedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\RecordList\DownloadPreset::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/DownloadPreset.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\Tree\Repository\AfterRawPageRowPreparedEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/AfterRawPageRowPreparedEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\Authentication\Event\PasswordHasBeenResetEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/PasswordHasBeenResetEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\Tree\Repository\BeforePageTreeIsFilteredEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/BeforePageTreeIsFilteredEvent.rst.txt',
        'withCode' => false,
    ],
    [
        'action' => 'createPhpClassDocs',
        'class' => \TYPO3\CMS\Backend\Search\Event\BeforeLiveSearchFormIsBuiltEvent::class,
        'targetFileName' => 'CodeSnippets/Events/Backend/BeforeLiveSearchFormIsBuiltEvent.rst.txt',
        'withCode' => false,
    ],
];
