styles.templates.layoutRootPath: EXT:site_package/Resources/Private/ContentElements/Layouts
styles.templates.partialRootPath: EXT:site_package/Resources/Private/ContentElements/Partials
styles.templates.templateRootPath: EXT:site_package/Resources/Private/ContentElements/Templates
styles.content.textmedia.maxW: 1200
styles.content.textmedia.maxWInText: 600
styles.content.textmedia.linkWrap.lightboxEnabled: true
styles.content.textmedia.linkWrap.lightboxCssClass: lightbox
