categories:
  MyExtension:
    label: 'My Extension' # (1)
  MyExtension.templates:
    label: 'Templates' # (2)
    parent: MyExtension
  MyExtension.pages:
    label: 'Pages'
    parent: MyExtension

settings:
  myExtension.templateRootPath:  # (5)
    label: 'Templates' # (3)
    category: MyExtension.templates # (2)
    description: 'Path to template root'  # (4)
    type: string  # (6)
    default: 'EXT:my_extension/Resources/Private/Templates/'  # (8), unless overridden by a set
  myExtension.partialRootPath:
    label: 'Partials'
    category: MyExtension.templates
    description: 'Path to partial root'
    type: string
    default: 'EXT:my_extension/Resources/Private/Partials/'  # (7)
