settings:
  example.types.text:
    type: text
    default: 'EXT:example/Resources/Private/Templates/'
    category: Example.types
    label: 'Type text'
    description: 'Uses the same validation and conversion as the `string` type,
    but identifies the setting as longer text in the editor.'
