name: test documentation

on:
  push:
  pull_request:

jobs:
  render:
    uses: TYPO3-Documentation/.github/.github/workflows/reusable-test-documentation.yml@main
    with:
      render-flags: '--no-progress --minimal-test'
